'use client'

import Link from 'next/link'
import { ArrowRight, Check, Eye, EyeOff, Sparkles } from 'lucide-react'
import { FormEvent, useState } from 'react'

export default function SignupPage() {
  const [showPassword, setShowPassword] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  return <main className="auth-shell"><div className="auth-aside"><Link href="/" className="marketing-brand"><span className="brand-mark"><Sparkles size={17} /></span><span>Afya<strong>Flow</strong></span></Link><div className="auth-quote"><span className="section-kicker">A clearer way to work</span><h1>More time for what matters.</h1><p>AfyaFlow helps your team run every part of the pharmacy day with confidence.</p><div className="quote-list"><span><Check size={15} /> Sales and stock in sync</span><span><Check size={15} /> M-Pesa ready from day one</span><span><Check size={15} /> Built for Kenyan pharmacies</span></div></div><small>© 2024 AfyaFlow</small></div><div className="auth-panel"><div className="auth-form-wrap"><div className="auth-mobile-brand"><Link href="/" className="marketing-brand"><span className="brand-mark"><Sparkles size={17} /></span><span>Afya<strong>Flow</strong></span></Link></div><span className="section-kicker">Start your free trial</span><h2>Create your account</h2><p className="auth-subtitle">Get your pharmacy moving in minutes. No credit card required.</p>{submitted ? <div className="auth-success"><span><Check size={18} /></span><h3>You&apos;re on your way.</h3><p>Your account setup is ready to continue. Connect your pharmacy details from the workspace.</p><Link href="/dashboard" className="primary-cta">Open AfyaFlow <ArrowRight size={16} /></Link></div> : <form onSubmit={submit}><label>Full name<input required placeholder="Jane Mwangi" /></label><label>Pharmacy name<input required placeholder="ABC Chemist" /></label><label>Work email<input required type="email" placeholder="jane@abcchemist.co.ke" /></label><label>Password<div className="password-field"><input required minLength={8} type={showPassword ? 'text' : 'password'} placeholder="8+ characters" /><button type="button" aria-label="Toggle password visibility" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff /> : <Eye />}</button></div></label><button className="primary-cta auth-submit" type="submit">Create account <ArrowRight size={16} /></button><p className="legal-copy">By creating an account, you agree to our Terms and Privacy Policy.</p></form>}<p className="auth-switch">Already have an account? <Link href="/login">Log in</Link></p></div></div></main>
}
